spring:
  profiles:
    active: local
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mydatabase?user=root&serverTimezone=UTC
    username: root
    password: 0529
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.jdbc: debug
file:
  path: /Users/wj/FileUploadPractice/
  #path: C:\\ShopImageFile

