version: "3"
services:
  shopapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
    networks:
      - mysqlnetwork

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: 1234
      restart: always
    ports:
      - "3306:3306"
    networks:
      - mysqlnetwork

networks:
  mysqlnetwork: